version: '3.8'

services:

  inventory-service:
    image: inventory-service:0.0.1-SNAPSHOT
    container_name: inventory-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    network_mode: inventory
